### ISSUE TITLE
Dockerfile build issue

### ISSUE THREAD

**Issue by srozb** [vlall/darksearch#4]
seems like there is no add-apt-repository in default ubuntu:14.04 docker image.

```
Status: Downloaded newer image for ubuntu:14.04
 ---> 14b59d36bae0
Step 2 : MAINTAINER Vishal Lall "vishal.h.lall@gmail.com"
 ---> Running in 40dc37b7a1e0
 ---> 2374f7998cd2
Removing intermediate container 40dc37b7a1e0
Step 3 : RUN add-apt-repository ppa:webupd8team/java
 ---> Running in 93a52e34bf3f
/bin/sh: 1: add-apt-repository: not found
```

This can be fixed running:

```
apt-get install -y software-properties-common
```

before the ```add-apt-repository```

Please verify your dockerfile builds correctly.

**Comment by vlall** [comment]
Good find! This problem is now fixed along with a few other updates to the Dockerfile. Feel free to make a PR next time.
